### ISSUE TITLE
adding newline to end of file in YAS mode

### ISSUE THREAD

**Issue by 54696d21** [singularitti/vscode-julia-formatter#34]
when I set the extension to YAS mode and invoke the formatter, it does not add a newline to the end of the file, although that would be necessary to comply with YAS (if I understand it correctly)
> "All files should have newline character at the end of the file"

**Comment by singularitti** [comment]
I see, the reason is we currently use [`format_text` to format the string read from a file](https://github.com/singularitti/vscode-julia-formatter/blob/63017b0ee03feb71942a0fa95b43e0f40c13e6e6/src/extension.ts#L144), rather the `format_file` we used before version 0.3.0. So `format_text` cannot know it is a file but `format_file` can. The problem was introduced because of [this PR](https://github.com/singularitti/vscode-julia-formatter/pull/19/files).

**Comment by singularitti** [comment]
Hey guys @54696d21, the latest (1.5.0+) julia-vscode plugin already supports JuliaFormatter.jl as its default formatter. Could you try that?
